name: Test and Lint

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["main", "develop"]

jobs:
  test-and-lint-matrix:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv and other tools
        run: |
          python -m pip install --upgrade pip
          pip install uv ruff

      - name: Lint with ruff
        run: |
          uv run ruff check

      - name: Run tests with uv
        run: |
          uv sync --extra dev
          uv run pytest

  test-and-lint-single:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install uv and other tools
        run: |
          python -m pip install --upgrade pip
          pip install uv ruff

      - name: Lint with ruff
        run: |
          uv run ruff check

      - name: Run tests with uv
        run: |
          uv sync --extra dev
          uv run pytest
